name: Create AppImage

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: sudo apt update && sudo apt install ninja-build

      - run: packages/logbook_app/tool/build_linux.sh

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|experimental-software|logbook|latest|*x86_64.AppImage.zsync
        with:
          recipe: packages/logbook_app/AppImageBuilder.yml

      - name: Upload AppImage to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "packages/logbook_app/*.AppImage"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
