name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest
            output-name: ./packages/logbook_app/build/macos/Build/Products/Release/logbook.app

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build release
        run: ./tool/build.sh

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ matrix.output-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
