name: Create AppImage

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: sudo apt update && sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - run: ./packages/logbook_app/tool/build_linux.sh

      - run: ./packages/logbook_app/tool/build_appimage.sh

      - name: Upload AppImage to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./packages/logbook_app/Logbook*.AppImage"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
