name: Create Linux release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Flutter Linux build dependencies
        run: sudo apt update && sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Build Flutter Linux app
        run: ./packages/logbook_app/tool/build_linux.sh
      - name: Create binary package
        run: |
          RELEASE_VERSION=$(echo ${GITHUB_REF}  | sed -n -e 's|refs/tags/\(.*\)|\1|p')
          TAR_FILE="logbookapp-${RELEASE_VERSION}-linux-x86_64.tar.gz"
          BINARY_DIR="packages/logbook_app/build/linux/x64/release/bundle/"
          tar czf ${TAR_FILE} --directory=${BINARY_DIR} .
        shell: bash
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./*.tar.gz"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
