on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup
        run: sudo snap install snapcraft --classic && sudo snap install lxd
      - name: Init LXD
        uses: bonddim/action-lxd-init@v1
      - name: Allow-list build dir
        run: git config --global --add safe.directory '*'
      - name: Compile
        run: snapcraft --use-lxd
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.snap"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
