name: Create AppImage

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Flutter Linux build dependencies
        run: sudo apt update && sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Build Flutter Linux app
        run: ./packages/logbook_app/tool/build_linux.sh
      - name: Create binary package
        run: tar czf logbookapp-${GITHUB_REF}-linux-x86_64.tgz --directory=packages/logbook_app/build/linux/x64/release/bundle/ .
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./*.tgz"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
