name: Pull Request Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dart-test:
    name: Run tests
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'docs') and github.event.pull_request.draft == false"
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: ./tool/test.sh
